# Generated by Django 4.1.5 on 2023-01-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_remove_fotografia_descricao_remove_fotografia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='descricao',
            field=models.TextField(blank='False', max_length=300),
        ),
    ]
