# Generated by Django 4.1.5 on 2023-01-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0010_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='preco',
            field=models.IntegerField(blank='False', default=0),
        ),
    ]
